<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
    <PackageReference Include="PublicApiGenerator"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="Verify.XunitV3"/>
    <PackageReference Include="xunit.v3"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpVision.Document\SharpVision.Document.csproj"/>
    <ProjectReference Include="..\..\src\SharpVision.FigletFonts\SharpVision.FigletFonts.csproj"/>
    <ProjectReference Include="..\..\src\SharpVision.Terminal\SharpVision.Terminal.csproj"/>
    <ProjectReference Include="..\..\src\SharpVision\SharpVision.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>OverallVersion</_Parameter1>
      <_Parameter2>$(OverallVersion)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
