// Copyright (c) SharpVision contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// <auto-generated />
// Unicode 17.0.0; generated by scripts/generate-unicode-data.mjs.

namespace SharpVision.Terminal.Unicode;

/// <summary>Identifies a Unicode East Asian Width property.</summary>
internal enum EastAsianWidth
{
    /// <summary>A neutral-width scalar.</summary>
    Neutral,
    /// <summary>An ambiguous-width scalar.</summary>
    Ambiguous,
    /// <summary>A fullwidth scalar.</summary>
    Fullwidth,
    /// <summary>A halfwidth scalar.</summary>
    Halfwidth,
    /// <summary>A narrow scalar.</summary>
    Narrow,
    /// <summary>A wide scalar.</summary>
    Wide,
}
