// Copyright (c) SharpVision contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// <auto-generated />
// Unicode 17.0.0; generated by scripts/generate-unicode-data.mjs.

namespace SharpVision.Terminal.Unicode;

/// <summary>Identifies a Unicode grapheme-cluster break property.</summary>
internal enum GraphemeBreak
{
    /// <summary>No explicit break property applies.</summary>
    Other,

    /// <summary>A prepended mark.</summary>
    Prepend,

    /// <summary>A carriage return.</summary>
    Cr,

    /// <summary>A line feed.</summary>
    Lf,

    /// <summary>A control or format scalar.</summary>
    Control,

    /// <summary>An extending scalar.</summary>
    Extend,

    /// <summary>A regional indicator.</summary>
    RegionalIndicator,

    /// <summary>A spacing combining mark.</summary>
    SpacingMark,

    /// <summary>A Hangul leading consonant.</summary>
    L,

    /// <summary>A Hangul vowel.</summary>
    V,

    /// <summary>A Hangul trailing consonant.</summary>
    T,

    /// <summary>A Hangul leading-vowel syllable.</summary>
    Lv,

    /// <summary>A Hangul leading-vowel-trailing syllable.</summary>
    Lvt,

    /// <summary>A zero-width joiner.</summary>
    Zwj
}
