// Copyright (c) SharpVision contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// <auto-generated />
// Unicode 17.0.0; generated by scripts/generate-unicode-data.mjs.

namespace SharpVision.Terminal.Unicode;

/// <summary>Identifies an Indic conjunct-break property.</summary>
internal enum IndicConjunct
{
    /// <summary>No Indic conjunct property applies.</summary>
    None,

    /// <summary>A conjunct linker.</summary>
    Linker,

    /// <summary>A conjunct consonant.</summary>
    Consonant,

    /// <summary>A conjunct extender.</summary>
    Extend
}
