// Copyright (c) SharpVision contributors. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// <auto-generated />
// Unicode 17.0.0; generated by scripts/generate-unicode-data.mjs.

namespace SharpVision.Terminal.Unicode;

using System.Diagnostics;

/// <summary>Stores one inclusive scalar range and its generated property value.</summary>
internal readonly record struct PropertyRange
{
    /// <summary>Initializes one generated inclusive scalar range.</summary>
    /// <param name="start">The first Unicode scalar.</param>
    /// <param name="end">The last Unicode scalar.</param>
    /// <param name="value">The generated enum or Boolean value.</param>
    internal PropertyRange(int start, int end, int value)
    {
        Debug.Assert(start >= 0, "A generated scalar range cannot start below zero.");
        Debug.Assert(end >= start, "A generated scalar range cannot end before it starts.");
        Debug.Assert(end <= 0x10FFFF, "A generated scalar range must end within Unicode.");

        Start = start;
        End = end;
        Value = value;
    }

    /// <summary>Gets the first Unicode scalar.</summary>
    internal int Start { get; }

    /// <summary>Gets the last Unicode scalar.</summary>
    internal int End { get; }

    /// <summary>Gets the generated enum or Boolean value.</summary>
    internal int Value { get; }
}
