// <auto-generated />
// Unicode 17.0.0; generated by scripts/generate-unicode-data.mjs.

namespace SharpVision.Terminal.Unicode;

/// <summary>Stores one inclusive scalar range and its generated property value.</summary>
/// <param name="Start">The first Unicode scalar.</param>
/// <param name="End">The last Unicode scalar.</param>
/// <param name="Value">The generated enum or Boolean value.</param>
internal readonly record struct PropertyRange(int Start, int End, int Value);
