<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
    <PackageReference Include="Shouldly"/>
    <PackageReference Include="xunit.v3"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpVision.Document\SharpVision.Document.csproj"/>
    <ProjectReference Include="..\..\src\SharpVision\SharpVision.csproj"/>
    <ProjectReference Include="..\SharpVision.Test.Shared\SharpVision.Test.Shared.csproj"/>
  </ItemGroup>

</Project>
