<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SharpVision.Terminal\SharpVision.Terminal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../extern/figlet/figlet-fonts.zip" Link="Fonts/figlet-fonts.zip" LogicalName="SharpVision.Fonts.figlet-fonts.zip" />
    <EmbeddedResource Include="../../extern/figlet/fonts.manifest.json" Link="Fonts/fonts.manifest.json" LogicalName="SharpVision.Fonts.fonts.manifest.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
